const fs = require('fs');
const code = `// ProTrading Journal
var STORAGE_KEYS={TRADES:"protrade_trades",SETTINGS:"protrade_settings",NOTES:"protrade_notes",CHECKLIST:"protrade_checklist"};
var DEFAULT_SETTINGS={initialCapital:10000,theme:"light"};
var state={trades:[],settings:Object.assign({},DEFAULT_SETTINGS),notes:[],checklist:{},currentSection:"dashboard"};
var equityChart=null;var pairChart=null;var zoomLevel=100;var currentTimeRange="all";var currentChartRange="all";
document.addEventListener("DOMContentLoaded",function(){loadData();initializeApp();setupEventListeners();updateUI()});
function loadData(){try{state.trades=JSON.parse(localStorage.getItem(STORAGE_KEYS.TRADES))||[];state.settings=JSON.parse(localStorage.getItem(STORAGE_KEYS.SETTINGS))||Object.assign({},DEFAULT_SETTINGS);state.notes=JSON.parse(localStorage.getItem(STORAGE_KEYS.NOTES))||[];state.checklist=JSON.parse(localStorage.getItem(STORAGE_KEYS.CHECKLIST))||{}}catch(e){console.error(e)}}
function saveData(){try{localStorage.setItem(STORAGE_KEYS.TRADES,JSON.stringify(state.trades));localStorage.setItem(STORAGE_KEYS.SETTINGS,JSON.stringify(state.settings));localStorage.setItem(STORAGE_KEYS.NOTES,JSON.stringify(state.notes));localStorage.setItem(STORAGE_KEYS.CHECKLIST,JSON.stringify(state.checklist))}catch(e){console.error(e)}}
function initializeApp(){document.documentElement.setAttribute("data-theme",state.settings.theme);document.getElementById("tradeDate").value=new Date().toISOString().slice(0,16);document.getElementById("initialCapital").value=state.settings.initialCapital;var themeBtn=document.getElementById("themeToggle");if(state.settings.theme==="dark"){themeBtn.innerHTML='<i class="fas fa-sun"></i><span>Mode Clair</span>'}else{themeBtn.innerHTML='<i class="fas fa-moon"></i><span>Mode Sombre</span>'}initCharts();renderChecklist();renderNotes()}
function setupEventListeners(){document.querySelectorAll(".nav-item").forEach(function(item){item.addEventListener("click",handleNavigation)});document.getElementById("themeToggle").addEventListener("click",toggleTheme);document.getElementById("menuToggle").addEventListener("click",function(){document.getElementById("sidebar").classList.toggle("active")});document.getElementById("tradeForm").addEventListener("submit",handleTradeSubmit);document.getElementById("clearForm").addEventListener("click",clearTradeForm);document.getElementById("stopLoss").addEventListener("input",calculateRR);document.getElementById("takeProfit").addEventListener("input",calculateRR);document.getElementById("filterPair").addEventListener("change",filterTrades);document.getElementById("filterType").addEventListener("change",filterTrades);document.getElementById("filterResult").addEventListener("change",filterTrades);document.getElementById("filterDate").addEventListener("change",filterTrades);document.getElementById("filterTag").addEventListener("change",filterTrades);document.getElementById("clearFilters").addEventListener("click",clearFilters);document.getElementById("exportCSV").addEventListener("click",exportCSV);document.getElementById("exportPDF").addEventListener("click",exportPDF);document.querySelectorAll(".time-btn").forEach(function(btn){btn.addEventListener("click",handleTimeRange)});document.querySelectorAll(".chart-btn").forEach(function(btn){btn.addEventListener("click",handleChartRange)});document.getElementById("saveCapital").addEventListener("click",saveCapital);document.getElementById("exportAllData").addEventListener("click",exportAllData);document.getElementById("clearAllData").addEventListener("click",clearAllData);document.getElementById("resetChecklist").addEventListener("click",resetChecklist);document.getElementById("saveChecklist").addEventListener("click",saveChecklistState);document.getElementById("addNote").addEventListener("click",openNoteModal);document.getElementById("addFirstNote").addEventListener("click",openNoteModal);document.getElementById("cancelNote").addEventListener("click",closeNoteModal);document.getElementById("saveNote").addEventListener("click",saveNote);document.getElementById("closeNoteModal").addEventListener("click",closeNoteModal);document.getElementById("closeModal").addEventListener("click",closeImageModal);document.getElementById("zoomIn").addEventListener("click",function(){handleZoom(10)});document.getElementById("zoomOut").addEventListener("click",function(){handleZoom(-10)});document.getElementById("resetZoom").addEventListener("click",resetZoom);document.getElementById("imageModal").addEventListener("click",function(e){if(e.target.id==="imageModal")closeImageModal()});document.getElementById("noteModal").addEventListener("click",function(e){if(e.target.id==="noteModal")closeNoteModal()})}
function handleNavigation(e){e.preventDefault();var target=e.currentTarget.dataset.section;if(!target)return;document.querySelectorAll(".nav-item").forEach(function(item){item.classList.remove("active")});e.currentTarget.classList.add("active");document.querySelectorAll(".content-section").forEach(function(section){section.classList.remove("active")});document.getElementById(target).classList.add("active");var titles={"dashboard":"Dashboard","add-trade":"Ajouter un Trade","trades":"Mes Trades","stats":"Statistiques","checklist":"Checklist Avant Trade","notes":"Notes de Marche","settings":"Parametres"};document.querySelector(".header-title h1").textContent=titles[target]||"Dashboard";document.getElementById("sidebar").classList.remove("active");state.currentSection=target;if(target==="trades"){renderTradesTable()}else if(target==="stats"){updateDetailedStats()}}
function toggleTheme(){state.settings.theme=state.settings.theme==="light"?"dark":"light";document.documentElement.setAttribute("data-theme",state.settings.theme);var themeBtn=document.getElementById("themeToggle");if(state.settings.theme==="dark"){themeBtn.innerHTML='<i class="fas fa-sun"></i><span>Mode Clair</span>'}else{themeBtn.innerHTML='<i class="fas fa-moon"></i><span>Mode Sombre</span>'}saveData();updateCharts()}
function handleTradeSubmit(e){e.preventDefault();var trade={id:Date.now(),date:document.getElementById("tradeDate").value,pair:document.getElementById("pair").value,tradeType:document.getElementById("tradeType").value,tradingType:document.getElementById("tradingType").value,lotSize:parseFloat(document.getElementById("lotSize").value)||0,riskPercent:parseFloat(document.getElementById("riskPercent").value)||0,stopLoss:parseFloat(document.getElementById("stopLoss").value)||0,takeProfit:parseFloat(document.getElementById("takeProfit").value)||0,rr:calculateRRValue(),result:parseFloat(document.getElementById("result").value)||0,resultPercent:parseFloat(document.getElementById("resultPercent").value)||0,tags:getSelectedTags(),comment:document.getElementById("comment").value,screenshot:null};var screenshotInput=document.getElementById("screenshot");if(screenshotInput.files&&screenshotInput.files[0]){var reader=new FileReader();reader.onload=function(event){trade.screenshot=event.target.result;saveTrade(trade)};reader.readAsDataURL(screenshotInput.files[0])}else{saveTrade(trade)}}
function saveTrade(trade){state.trades.push(trade);saveData();showToast("Trade enregistre!","success");clearTradeForm();updateUI();document.querySelector('[data-section="trades"]').click()}
function calculateRRValue(){var sl=parseFloat(document.getElementById("stopLoss").value)||0;var tp=parseFloat(document.getElementById("takeProfit").value)||0;return sl>0?(tp/sl).toFixed(2):"0.00"}
function calculateRR(){var sl=parseFloat(document.getElementById("stopLoss").value)||0;var tp=parseFloat(document.getElementById("takeProfit").value)||0;if(sl>0&&tp>0){document.getElementById("rrDisplay").value="1:"+(tp/sl).toFixed(2)}else{document.getElementById("rrDisplay").value="1:0"}}
function getSelectedTags(){var checkboxes=document.querySelectorAll('input[name="tags"]:checked');return Array.from(checkboxes).map(function(cb){return cb.value})}
function clearTradeForm(){document.getElementById("tradeForm").reset();document.getElementById("tradeDate").value=new Date().toISOString().slice(0,16);document.getElementById("rrDisplay").value="";document.getElementById("result").value="";document.getElementById("resultPercent").value=""}
function deleteTrade(tradeId){if(!confirm("Etes-vous sur?"))return;state.trades=state.trades.filter(function(t){return t.id!==tradeId});saveData();updateUI();renderTradesTable();showToast("Trade supprime","success")}
function viewTradeScreenshot(tradeId){var trade=state.trades.find(function(t){return t.id===tradeId});if(trade&&trade.screenshot){document.getElementById("modalImage").src=trade.screenshot;document.getElementById("imageModal").classList.add("active");resetZoom()}}
function closeImageModal(){document.getElementById("imageModal").classList.remove("active")}
function handleZoom(delta){zoomLevel=Math.max(50,Math.min(200,zoomLevel+delta));document.getElementById("zoomLevel").textContent=zoomLevel+"%";document.getElementById("modalImage").style.transform="scale("+(zoomLevel/100)+")"}
function resetZoom(){zoomLevel=100;document.getElementById("zoomLevel").textContent="100%";document.getElementById("modalImage").style.transform="scale(1)"}
function filterTrades(){renderTradesTable()}
function clearFilters(){document.getElementById("filterPair").value="";document.getElementById("filterType").value="";document.getElementById("filterResult").value="";document.getElementById("filterDate").value="";document.getElementById("filterTag").value="";renderTradesTable()}
function getFilteredTrades(){var pair=document.getElementById("filterPair").value;var type=document.getElementById("filterType").value;var result=document.getElementById("filterResult").value;var date=document.getElementById("filterDate").value;var tag=document.getElementById("filterTag").value;return state.trades.filter(function(trade){if(pair&&trade.pair!==pair)return false;if(type&&trade.tradeType!==type)return false;if(result==="win"&&trade.result<=0)return false;if(result==="loss"&&trade.result>=0)return false;if(result==="breakeven"&&trade.result!==0)return false;if(date&&trade.date.slice(0,10)!==date)return false;if(tag&&!trade.tags.includes(tag))return false;return true})}
function calculateStats(trades){trades=trades||state.trades;if(trades.length===0){return{totalTrades:0,wins:0,losses:0,winrate:0,totalProfit:0,grossProfit:0,grossLoss:0,profitFactor:0,avgWin:0,avgLoss:0,maxWin:0,maxLoss:0,drawdown:0,disciplineScore:0}}var wins=trades.filter(function(t){return t.result>0});var losses=trades.filter(function(t){return t.result<0});var grossProfit=wins.reduce(function(sum,t){return sum+t.result},0);var grossLoss=Math.abs(losses.reduce(function(sum,t){return sum+t.result},0));var totalProfit=trades.reduce(function(sum,t){return sum+t.result},0);var maxWin=Math.max(0,...trades.map(function(t){return t.result}));var maxLoss=Math.min(0,...trades.map(function(t){return t.result}));var initialCapital=state.settings.initialCapital;var peak=initialCapital;var drawdown=0;trades.forEach(function(trade){initialCapital+=trade.result;if(initialCapital>peak)peak=initialCapital;var dd=(peak-initialCapital)/peak*100;if(dd>drawdown)drawdown=dd});var disciplineScore=calculateDisciplineScore(trades);return{totalTrades:trades.length,wins:wins.length,losses:losses.length,winrate:trades.length>0?(wins.length/trades.length*100).toFixed(1):0,totalProfit:totalProfit.toFixed(2),grossProfit:grossProfit.toFixed(2),grossLoss:grossLoss.toFixed(2),profitFactor:grossLoss>0?(grossProfit/grossLoss).toFixed(2):grossProfit>0?"inf":"0.00",avgWin:wins.length>0?(grossProfit/wins.length).toFixed(2):0,avgLoss:losses.length>0?(grossLoss/losses.length).toFixed(2):0,maxWin:maxWin.toFixed(2),maxLoss:maxLoss.toFixed(2),drawdown:drawdown.toFixed(1),disciplineScore:disciplineScore}}
function calculateDisciplineScore(trades){if(trades.length===0)return 0;var score=0;var goodRR=trades.filter(function(t){return parseFloat(t.rr)>=3}).length;score+=(goodRR/trades.length)*40;var withComments=trades.filter(function(t){return t.comment&&t.comment.length>10}).length;score+=(withComments/trades.length)*30;var withTags=trades.filter(function(t){return t.tags&&t.tags.length>0}).length;score+=(withTags/trades.length)*30;return Math.round(score)}
function updateDetailedStats(){var stats=calculateStats();document.getElementById("detailWinrate").textContent=stats.winrate+"%";document.getElementById("detailProfitFactor").textContent=stats.profitFactor;document.getElementById("detailAvgWin").textContent="$"+stats.avgWin;document.getElementById("detailAvgLoss").textContent="$"+stats.avgLoss;var avgRR=state.trades.length>0?(state.trades.reduce(function(sum,t){return sum+parseFloat(t.rr||0)},0)/state.trades.length).toFixed(1):0;document.getElementById("detailAvgRR").textContent="1:"+avgRR;var consecutiveWins=0,consecutiveLosses=0,currentWins=0,currentLosses=0;state.trades.forEach(function(trade){if(trade.result>0){currentWins++;currentLosses=0;if(currentWins>consecutiveWins)consecutiveWins=currentWins}else if(trade.result<0){currentLosses++;currentWins=0;if(currentLosses>consecutiveLosses)consecutiveLosses=currentLosses}else{currentWins=0;currentLosses=0}});document.getElementById("detailConsecutiveWins").textContent=consecutiveWins;document.getElementById("detailConsecutiveLosses").textContent=consecutiveLosses;document.getElementById("detailMaxWin").textContent="$"+stats.maxWin;updateStatsByPair();updateStatsByType();updateStatsByRR()}
function updateStatsByPair(){var container=document.getElementById("statsByPair");var pairStats={};state.trades.forEach(function(trade){if(!pairStats[trade.pair]){pairStats[trade.pair]={trades:0,wins:0,profit:0}}pairStats[trade.pair].trades++;if(trade.result>0)pairStats[trade.pair].wins++;pairStats[trade.pair].profit+=trade.result});if(Object.keys(pairStats).length===0){container.innerHTML='<div class="empty-state small"><p>Aucune donnee</p></div>';return}var html="";for(var pair in pairStats){var stats=pairStats[pair];var winrate=((stats.wins/stats.trades)*100).toFixed(0);var profitClass=stats.profit>=0?"positive":"negative";html+='<div class="breakdown-item"><span class="breakdown-pair">'+pair+'</span><span class="breakdown-value '+profitClass+'">$'+stats.profit.toFixed(2)+" ("+winrate+"%)</span></div>"}container.innerHTML=html}
function updateStatsByType(){var container=document.getElementById("statsByType");var typeStats={};state.trades.forEach(function(trade){if(!typeStats[trade.tradingType]){typeStats[trade.tradingType]={trades:0,wins:0,profit:0}}typeStats[trade.tradingType].trades++;if(trade.result>0)typeStats[trade.tradingType].wins++;typeStats[trade.tradingType].profit+=trade.result});if(Object.keys(typeStats).length===0){container.innerHTML='<div class="empty-state small"><p>Aucune donnee</p></div>';return}var html="";for(var type in typeStats){var stats=typeStats[type];var winrate=((stats.wins/stats.trades)*100).toFixed(0);var profitClass=stats.profit>=0?"positive":"negative";html+='<div class="breakdown-item"><span class="breakdown-pair">'+type+'</span><span class="breakdown-value '+profitClass+'">$'+stats.profit.toFixed(2)+" ("+winrate+"%)</span></div>"}container.innerHTML=html}
function updateStatsByRR(){var container=document.getElementById("statsByRR");var rrStats={"<1:1":{trades:0,wins:0,profit:0},"1:1-1:2":{trades:0,wins:0,profit:0},"1:2-1:3":{trades:0,wins:0,profit:0},">1:3":{trades:0,wins:0,profit:0}};state.trades.forEach(function(trade){var rr=parseFloat(trade.rr)||0;var category;if(rr<1)category="<1:1";else if(rr<2)category="1:1-1:2";else if(rr<3)category="1:2-1:3";else category=">1:3";rrStats[category].trades++;if(trade.result>0)rrStats[category].wins++;rrStats[category].profit+=trade.result});var hasData=Object.values(rrStats).some(function(s){return s.trades>0});if(!hasData){container.innerHTML='<div class="empty-state small"><p>Aucune donnee</p></div>';return}var html="";for(var rr in rrStats){var stats=rrStats[rr];var winrate=stats.trades>0?((stats.wins/stats.trades)*100).toFixed(0):0;var profitClass=stats.profit>=0?"positive":"negative";html+='<div class="breakdown-item"><span class="breakdown-pair">'+rr+'</span><span class="breakdown-value '+profitClass+'">$'+stats.profit.toFixed(2)+" ("+winrate+"%)</span></div>"}container.innerHTML=html}
function handleTimeRange(e){var range=e.target.dataset.range;if(!range)return;document.querySelectorAll(".time-btn").forEach(function(btn){btn.classList.remove("active")});e.target.classList.add("active");currentTimeRange=range;updateStatsByTimeRange()}
function updateStatsByTimeRange(){var filteredTrades=getTradesByTimeRange();var stats=calculateStats(filteredTrades);document.getElementById("totalTrades").textContent=stats.totalTrades;document.getElementById("winrate").textContent=stats.winrate+"%";document.getElementById("totalProfit").textContent=(stats.totalProfit>=0?"+":"")+"$"+stats.totalProfit;document.getElementById("totalProfit").className="stat-value "+(stats.totalProfit>=0?"positive":"negative");document.getElementById("profitFactor").textContent=stats.profitFactor;document.getElementById("disciplineScore").textContent=stats.disciplineScore+"/100"}
function getTradesByTimeRange(){if(currentTimeRange==="all")return state.trades;var now=new Date();var startDate=new Date();switch(currentTimeRange){case"today":startDate.setHours(0,0,0,0);break;case"week":startDate.setDate(now.getDate()-7);break;case"month":startDate.setMonth(now.getMonth()-1);break}return state.trades.filter(function(trade){var tradeDate=new Date(trade.date);return tradeDate>=startDate})}
function initCharts(){initEquityChart();initPairChart();updateCharts()}
function initEquityChart(){var ctx=document.getElementById("equityChart").getContext("2d");equityChart=new Chart(ctx,{type:"line",data:{labels:[],datasets:[{label:"Capital",data:[],borderColor:"#2563eb",backgroundColor:"rgba(37,99,235,0.1)",fill:true,tension:.4,pointRadius:3,pointHoverRadius:6}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{mode:"index",intersect:false,callbacks:{label:function(context){return"$"+context.parsed.y.toFixed(2)}}}},scales:{x:{grid:{display:false}},y:{grid:{color:"rgba(0,0,0,0.05)"},ticks:{callback:function(value){return"$"+value.toFixed(0)}}}}}})}
function initPairChart(){var ctx=document.getElementById("pairChart").getContext("2d");pairChart=new Chart(ctx,{type:"doughnut",data:{labels:[],datasets:[{data:[],backgroundColor:["#2563eb","#10b981","#f59e0b","#ef4444","#8b5cf6","#06b6d4"],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"right",labels:{usePointStyle:true,padding:20}}}}})}
function handleChartRange(e){var range=e.target.dataset.range;if(!range)return;document.querySelectorAll(".chart-btn").forEach(function(btn){btn.classList.remove("active")});e.target.classList.add("active");currentChartRange=range;updateCharts()}
function updateCharts(){updateEquityChart();updatePairChart()}
function updateEquityChart(){var trades=getTradesByChartRange();var initialCapital=state.settings.initialCapital;var labels=[];var data=[];var capital=initialCapital;trades.forEach(function(trade){capital+=trade.result;labels.push(new Date(trade.date).toLocaleDateString("fr-FR"));data.push(capital)});if(equityChart){equityChart.data.labels=labels;equityChart.data.datasets[0].data=data;equityChart.update()}}
function updatePairChart(){var pairCounts={};state.trades.forEach(function(trade){if(!pairCounts[trade.pair]){pairCounts[trade.pair]=0}pairCounts[trade.pair]++});var labels=Object.keys(pairCounts);var data=Object.values(pairCounts);if(pairChart){pairChart.data.labels=labels;pairChart.data.datasets[0].data=data;pairChart.update()}}
function getTradesByChartRange(){if(currentChartRange==="all")return state.trades;var now=new Date();var startDate=new Date();switch(currentChartRange){case"week":startDate.setDate(now.getDate()-7);break;case"month":startDate.setMonth(now.getMonth()-1);break;case"3months":startDate.setMonth(now.getMonth()-3);break}return state.trades.filter(function(trade){var tradeDate=new Date(trade.date);return tradeDate>=startDate})}
function updateUI(){var filteredTrades=getTradesByTimeRange();var stats=calculateStats(filteredTrades);document.getElementById("totalTrades").textContent=stats.totalTrades;document.getElementById("winrate").textContent=stats.winrate+"%";document.getElementById("totalProfit").textContent=(stats.totalProfit>=0?"+":"")+"$"+stats.totalProfit;document.getElementById("totalProfit").className="stat-value "+(stats.totalProfit>=0?"positive":"negative");document.getElementById("profitFactor").textContent=stats.profitFactor;document.getElementById("disciplineScore").textContent=stats.disciplineScore+"/100";renderRecentTrades();updateCharts()}
function renderTradesTable(){var trades=getFilteredTrades();var tbody=document.getElementById("tradesTableBody");if(trades.length===0){tbody.innerHTML='<tr><td colspan="8" class="empty-state">Aucun trade trouve</td></tr>';return}trades.sort(function(a,b){return new Date(b.date)-new Date(a.date)});var html="";trades.forEach(function(trade){var resultClass=trade.result>0?"positive":(trade.result<0?"negative":"");var resultPrefix=trade.result>0?"+":"";html+='<tr>';html+='<td>'+new Date(trade.date).toLocaleDateString("fr-FR")+'</td>';html+='<td><span class="pair-badge">'+trade.pair+'</span></td>';html+='<td><span class="type-'+trade.tradeType.toLowerCase()+'">'+trade.tradeType+'</span></td>';html+='<td>'+trade.lotSize+'</td>';html+='<td>1:'+trade.rr+'</td>';html+='<td class="'+resultClass+'">'+resultPrefix+'$'+trade.result.toFixed(2)+'</td>';html+='<td>';if(trade.screenshot){html+='<button class="btn-icon" onclick="viewTradeScreenshot('+trade.id+')" title="Voir capture"><i class="fas fa-image"></i></button>'}html+='<button class="btn-icon danger" onclick="deleteTrade('+trade.id+')" title="Supprimer"><i class="fas fa-trash"></i></button>';html+='</td>';html+='</tr>'});tbody.innerHTML=html}
function renderRecentTrades(){var recentTrades=state.trades.slice(-5).reverse();var container=document.getElementById("recentTrades");if(recentTrades.length===0){container.innerHTML='<div class="empty-state small"><p>Aucun trade recent</p></div>';return}var html="";recentTrades.forEach(function(trade){var resultClass=trade.result>0?"positive":(trade.result<0?"negative":"");html+='<div class="recent-trade-item">';html+='<div class="recent-trade-info">';html+='<span class="pair-badge small">'+trade.pair+'</span>';html+='<span class="type-'+trade.tradeType.toLowerCase()+' small">'+trade.tradeType+'</span>';html+='</div>';html+='<div class="recent-trade-result '+resultClass+'">';html+=(trade.result>0?"+":"")+'$'+trade.result.toFixed(2);html+='</div>';html+='</div>'});container.innerHTML=html}
function renderChecklist(){var checklistItems=document.querySelectorAll(".checklist-item input");var savedState=state.checklist||{};checklistItems.forEach(function(item){var id=item.id;item.checked=savedState[id]||false})}
function saveChecklistState(){var checklistItems=document.querySelectorAll(".checklist-item input");var savedState={};checklistItems.forEach(function(item){savedState[item.id]=item.checked});state.checklist=savedState;saveData();showToast("Checklist sauvegardee!","success")}
function resetChecklist(){var checklistItems=document.querySelectorAll(".checklist-item input");checklistItems.forEach(function(item){item.checked=false});state.checklist={};saveData();showToast("Checklist reinitalisee","success")}
function renderNotes(){var container=document.getElementById("notesList");var emptyState=document.getElementById("emptyNotes");if(state.notes.length===0){container.innerHTML="";if(emptyState)emptyState.style.display="block";return}if(emptyState)emptyState.style.display="none";state.notes.sort(function(a,b){return new Date(b.date)-new Date(a.date)});var html="";state.notes.forEach(function(note){html+='<div class="note-item">';html+='<div class="note-header">';html+='<span class="note-date">'+new Date(note.date).toLocaleDateString("fr-FR")+'</span>';html+='<button class="btn-icon danger" onclick="deleteNote('+note.id+')"><i class="fas fa-trash"></i></button>';html+='</div>';html+='<div class="note-content">'+note.content+'</div>';html+='</div>'});container.innerHTML=html}
function openNoteModal(){document.getElementById("noteModal").classList.add("active");document.getElementById("noteContent").value=""}
function closeNoteModal(){document.getElementById("noteModal").classList.remove("active")}
function saveNote(){var content=document.getElementById("noteContent").value.trim();if(!content){showToast("Veuillez entrer du contenu","error");return}var note={id:Date.now(),date:new Date().toISOString(),content:content};state.notes.push(note);saveData();closeNoteModal();renderNotes();showToast("Note sauvegardee!","success")}
function deleteNote(noteId){if(!confirm("Etes-vous sur?"))return;state.notes=state.notes.filter(function(n){return n.id!==noteId});saveData();renderNotes();showToast("Note supprimee","success")}
function saveCapital(){var capital=parseFloat(document.getElementById("initialCapital").value);if(isNaN(capital)||capital<=0){showToast("Veuillez entrer un capital valide","error");return}state.settings.initialCapital=capital;saveData();updateUI();showToast("Capital mis a jour!","success")}
function exportAllData(){var data={trades:state.trades,settings:state.settings,notes:state.notes,checklist:state.checklist,exportDate:new Date().toISOString()};var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="protrade_backup_"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(url);showToast("Donnees exportees!","success")}
function clearAllData(){if(!confirm("Etes-vous sur?"))return;state.trades=[];state.notes=[];state.checklist={};saveData();updateUI();showToast("Donnees effacees","success")}
function exportCSV(){var trades=getFilteredTrades();if(trades.length===0){showToast("Aucune donnee a exporter","error");return}var csv="Date,Paire,Type,Type Trading,Lot,Risque %,Stop Loss,Take Profit,RR,Resultat,Tags,Commentaire\n";trades.forEach(function(trade){var row=[trade.date,trade.pair,trade.tradeType,trade.tradingType,trade.lotSize,trade.riskPercent,trade.stopLoss,trade.takeProfit,trade.rr,trade.result,"\""+(trade.tags||[]).join(", ")+"\"","\""+(trade.comment||"").replace(/"/g,"\"\"")+"\""];csv+=row.join(",")+"\n"});var blob=new Blob([csv],{type:"text/csv;charset=utf-8;"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="protrade_trades_"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(url);showToast("Export CSV termine!","success")}
function exportPDF(){var trades=getFilteredTrades();if(trades.length===0){showToast("Aucune donnee a exporter","error");return}var stats=calculateStats(trades);var content="PROTRADING JOURNAL - RAPPORT\n=====================================\n\nDate: "+new Date().toLocaleDateString("fr-FR")+"\n\nSTATISTIQUES GLOBALES\n---------------------------------------\nTotal Trades: "+stats.totalTrades+"\nWinrate: "+stats.winrate+"%\nProfit Total: $"+stats.totalProfit+"\nProfit Factor: "+stats.profitFactor+"\nScore Discipline: "+stats.disciplineScore+"/100\n\nLISTE DES TRADES\n---------------------------------------\n";trades.forEach(function(trade,index){content+=(index+1)+". "+trade.pair+" - "+trade.tradeType+" - $"+trade.result.toFixed(2)+"\nDate: "+new Date(trade.date).toLocaleDateString("fr-FR")+"\nRR: 1:"+trade.rr+"\n";if(trade.comment)content+="Commentaire: "+trade.comment+"\n";content+="\n"});var blob=new Blob([content],{type:"text/plain;charset=utf-8;"});var url=URL.createObjectURL(blob);var a=document.createElement("a");a.href=url;a.download="protrade_rapport_"+new Date().toISOString().slice(0,10)+".txt";a.click();URL.revokeObjectURL(url);showToast("Export termine!","success")}
function showToast(message,type){var toast=document.getElementById("toast");toast.textContent=message;toast.className="toast toast-"+type+" show";setTimeout(function(){toast.classList.remove("show")},3000)}
fs.writeFileSync('app.js',code);
console.log('Done: app.js created');`;
fs.writeFileSync('create_app_temp.js',code);
console.log('Done');
